[package]
name = "netmon"
version = "0.1.0"
authors = ["majorz"]

[dependencies]
log = "0.4"
env_logger = "0.5"

[dependencies.clap]
version = "2.32"
default-features = false

[dependencies.error-chain]
version = "0.12"
default-features = false
